openapi: 3.0.0
info:
  title: CRUD for BanPay
  description: Documentation for  methods BanPay
  version: 0.1.9
servers:
  - url: http://localhost:8085/apidocs/#/
    description: Development Enviroment
paths:
  /users:
    get:
      summary: Returns a list of users.
      tags:
        - Users
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /makeUsers:
    post:
      summary: Returns a list of users.
      tags:
        - Users
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string